//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PortakEntities : DbContext
    {
        public PortakEntities()
            : base("name=PortakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_DogumGunuOlanKullanicilar> vw_DogumGunuOlanKullanicilar { get; set; }
    
        public virtual int sp_DogumGunuOlanlaraPuanYukle(Nullable<int> puan)
        {
            var puanParameter = puan.HasValue ?
                new ObjectParameter("Puan", puan) :
                new ObjectParameter("Puan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DogumGunuOlanlaraPuanYukle", puanParameter);
        }
    }
}
